from dataclasses import dataclass, field
from typing import Callable

from .cmd_run_decorator import CmdRunDecorator


@dataclass(frozen=True)
class CmdRunnerSpec:
    """
    A declarative, immutable description of a single command runner in a chain.

    This type is the canonical, structured representation of what `Conveyor.add_cmd_runner`
    accepts as positional/keyword arguments plus a decorator. It exists so that command
    chains can be described declaratively (for example, from configuration files or
    generated by tooling) and extended without adding new ad-hoc tuple shapes.

    Attributes:
        cmd_runner (Callable): The callable that processes `(x_stdout, x_stderr)` bytes
            and returns `(stdout, stderr)` bytes.
        args (tuple): Positional arguments passed to `cmd_runner` on invocation.
        kwargs (dict): Keyword arguments passed to `cmd_runner` on invocation.
        decorator (CmdRunDecorator | None): An optional decorator applied to `cmd_runner`
            before it is added to the chain. Maps to `Conveyor.add_cmd_runner`'s
            `cmd_runner_decorator` parameter.
    """

    cmd_runner: Callable
    args: tuple = ()
    kwargs: dict = field(default_factory=dict)
    decorator: CmdRunDecorator | None = None

    @classmethod
    def coerce(cls, value) -> "CmdRunnerSpec":
        """
        Normalize a value into a `CmdRunnerSpec`.

        Accepts an existing `CmdRunnerSpec` (returned unchanged) or one of the
        supported tuple shapes, where the first element is the command runner and the
        remaining elements are interpreted by type:

            - `(cmd_runner,)`
            - `(cmd_runner, args)`                where `args` is a `tuple`
            - `(cmd_runner, kwargs)`              where `kwargs` is a `dict`
            - `(cmd_runner, decorator)`           where `decorator` is a `CmdRunDecorator`
            - `(cmd_runner, args, kwargs)`
            - `(cmd_runner, args, decorator)`
            - `(cmd_runner, kwargs, decorator)`
            - `(cmd_runner, args, kwargs, decorator)`

        Args:
            value: A `CmdRunnerSpec` or one of the tuple shapes described above.

        Returns:
            CmdRunnerSpec: The normalized spec.

        Raises:
            TypeError: If `value` is neither a `CmdRunnerSpec` nor a non-empty tuple,
                if the first tuple element is not callable, if a trailing element is of
                an unexpected type, or if a trailing element's type appears more than
                once (ambiguous).
        """
        if isinstance(value, cls):
            return value

        if not isinstance(value, tuple) or not value:
            raise TypeError(
                f"Expected a CmdRunnerSpec or a non-empty tuple, got {value!r}."
            )

        cmd_runner, *rest = value
        if not callable(cmd_runner):
            raise TypeError(
                f"The first tuple element must be callable, got {cmd_runner!r}."
            )

        args, kwargs, decorator = (), {}, None
        args_set = kwargs_set = decorator_set = False

        for item in rest:
            if isinstance(item, tuple):
                if args_set:
                    raise TypeError(f"Ambiguous spec {value!r}: multiple args tuples.")
                args, args_set = item, True
            elif isinstance(item, dict):
                if kwargs_set:
                    raise TypeError(f"Ambiguous spec {value!r}: multiple kwargs dicts.")
                kwargs, kwargs_set = item, True
            elif isinstance(item, CmdRunDecorator):
                if decorator_set:
                    raise TypeError(f"Ambiguous spec {value!r}: multiple decorators.")
                decorator, decorator_set = item, True
            else:
                raise TypeError(
                    f"Unexpected element {item!r} in {value!r}; expected a tuple "
                    "(args), dict (kwargs), or CmdRunDecorator (decorator)."
                )

        return cls(cmd_runner, args, kwargs, decorator)
